# Generated by Django 2.1.5 on 2019-01-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=32)),
                ('recver', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='buyer/images')),
                ('vip', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodId', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('picture', models.ImageField(upload_to='image')),
                ('num', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=True, to='Buy.Buy')),
            ],
        ),
        migrations.CreateModel(
            name='CheckEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=32)),
                ('time', models.DateField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('time', models.DateTimeField(auto_now=True)),
                ('statue', models.CharField(max_length=32)),
                ('money', models.FloatField()),
                ('orderAddress', models.ForeignKey(on_delete=True, to='Buy.Address')),
                ('user', models.ForeignKey(on_delete=True, to='Buy.Buy')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsId', models.CharField(max_length=32)),
                ('goodsName', models.CharField(max_length=32)),
                ('goodsPrice', models.CharField(max_length=32)),
                ('goodsNum', models.CharField(max_length=32)),
                ('goodsPicture', models.CharField(max_length=32)),
                ('order', models.ForeignKey(on_delete=True, to='Buy.Order')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='buyer',
            field=models.ForeignKey(on_delete=True, to='Buy.Buy'),
        ),
    ]
